version: "3"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - flow-network

    next:
        build:
            context: .
            dockerfile: Dockerfile-nextjs
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            - /app/node_modules
        networks:
            - flow-network
        command: ["pnpm", "start:next"]

    ws:
        environment:
            - NODE_ENV=production
            - PORT=3001
        build:
            context: .
            dockerfile: Dockerfile-ws-server
        ports:
            - "3001:3001"
        depends_on:
            - postgres
        volumes:
            - /app/node_modules
        networks:
            - flow-network
        command: ["pnpm", "start:ws"]

volumes:
    postgres-data:

networks:
    flow-network:
        driver: bridge
