version: "3"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - flow-network

    app:
        image: ghcr.io/cestef/flow:latest
        ports:
            - "3000:3000"
            - "3001:3001"
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - flow-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres-data:

networks:
    flow-network:
        driver: bridge
