FROM node:18.17.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN pnpm --version
# Needed for prisma installation
RUN apt-get update -y && apt-get install -y openssl
COPY . /app

WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN --mount=type=cache,id=next,target=/app/.next/cache pnpm run build:next

FROM base

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/.next /app/.next

EXPOSE 3000

WORKDIR /app

